language: python
python:
- 3.6
env:
- DJANGO_VERSION=1.11.5
install:
- pip install -q Django==$DJANGO_VERSION
- pip install -r requirements.txt
before_script:
- flake8 --exclude='manage.py, acheumpet/settings.py, templates' .
script:
- python3 manage.py makemigrations
- python3 manage.py migrate
